stages:
  - setup
  - terraform

setup:
  stage: setup
  image: alpine:latest
  script:
    - echo "Exécution de commandes shell ici"
    - apk add --no-cache curl # Correction: Installation de 'curl' au lieu de 'quelquechose'

terraform_plan:
  stage: terraform
  image: hashicorp/terraform:1.2.0
  script:
    - terraform init
    - terraform plan
