stages:
  - plan
  - apply

variables:
  TF_VERSION: "1.2.0"

Terraform_plan:
  image: hashicorp/terraform:${TF_VERSION}
  stage: plan
  script:
    - terraform init
    - terraform plan
  only:
    - main

Terraform_apply:
  image: hashicorp/terraform:${TF_VERSION}
  stage: apply
  script:
    - terraform apply -auto-approve
  only:
    - main
