image: hashicorp/terraform:1.2.0

stages:
  - init
  - plan
  - apply

Terraform_init:
  stage: init
  script:
    - terraform init

Terraform_plan:
  stage: plan
  script:
    - terraform plan

Terraform_apply:
  stage: apply
  script:
    - terraform apply -auto-approve
