stages:
  - prepare
  - deploy

prepare:
  stage: prepare
  image: alpine:latest
  script:
    - echo "Running shell commands"
    - apk add --no-cache jq # Example of installing a package

deploy:
  stage: deploy
  image: hashicorp/terraform:1.2.0
  script:
    - terraform init
    - terraform plan
    - terraform apply
