stages:
  - init
  - plan
  - apply

before_script:
  - terraform --version
  - terraform init

Terraform_plan:
  stage: plan
  image: hashicorp/terraform:1.2.0
  script:
    - terraform plan -out=tfplan

Terraform_apply:
  stage: apply
  image: hashicorp/terraform:1.2.0
  script:
    - terraform apply -auto-approve tfplan
