stages:
  - prepare
  - deploy

prepare:
  image: alpine:latest
  stage: prepare
  script:
    - echo "Préparation de l'environnement"
    # Ajoutez ici d'autres commandes shell nécessaires à la préparation.

deploy:
  image: hashicorp/terraform:1.2.0
  stage: deploy
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
