stages:
  - deploy

variables:
  TF_VERSION: "1.2.0"
  # Assurez-vous de sécuriser vos variables d'environnement dans les paramètres CI/CD de GitLab.

before_script:
  - apt-get update && apt-get install -y wget unzip
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
  - terraform -v
  # Configurer les variables d'environnement pour Terraform

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  only:
    - main
